#!/usr/bin/env node
/**
 * Writes src/models.ts from the public HTTP docs catalog.
 * Default: https://docs.x.ai/developers/models.md
 */

import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(fileURLToPath(new URL("..", import.meta.url)));
const OUT = path.join(ROOT, "src/models.ts");
const DEFAULT_URL = "https://docs.x.ai/developers/models.md";
const UA = "Mozilla/5.0 (compatible; xai-sdk-ts/0.1)";

function modelsUrl() {
  return process.env.XAI_MODELS_URL ?? DEFAULT_URL;
}

function isLanguageModelId(id) {
  return (
    id.startsWith("grok-") &&
    !/imagine|video|voice|speech|tts|stt|embedding/i.test(id)
  );
}

function collectIds(markdown) {
  /** @type {Set<string>} */
  const ids = new Set();
  const add = (raw) => {
    const id = raw.trim().replace(/[).,;]+$/, "");
    if (!isLanguageModelId(id)) return;
    ids.add(id);
  };

  for (const match of markdown.matchAll(/grok-[a-z0-9]+(?:[._-][a-z0-9]+)*/gi)) {
    add(match[0]);
  }
  for (const match of markdown.matchAll(/\/developers\/models\/(grok-[a-z0-9._-]+)/gi)) {
    add(match[1]);
  }
  return [...ids].sort();
}

function render(ids, sourceUrl, sourceHash) {
  const body = ids.map((id) => `  | ${JSON.stringify(id)}`).join("\n");
  const fetchedAt = new Date().toISOString().slice(0, 10);
  return `/** Generated by \`pnpm generate:models\`. Do not edit by hand. */
/** Source: ${sourceUrl} (${fetchedAt}); SHA-256: ${sourceHash} */
export type KnownModelId =
${body};

/** Known model IDs with a forward-compatible escape hatch for newer releases. */
export type ModelId = KnownModelId | (string & {});
`;
}

async function main() {
  const url = modelsUrl();
  const response = await fetch(url, {
    headers: { accept: "*/*", "user-agent": UA },
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  const markdown = await response.text();
  const ids = collectIds(markdown);
  if (ids.length === 0) {
    throw new Error(`no language model ids found in ${url}`);
  }
  const sourceHash = createHash("sha256").update(markdown).digest("hex");
  await writeFile(OUT, render(ids, url, sourceHash));
  console.error(`wrote ${ids.length} models to src/models.ts`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
