#!/usr/bin/env node
/**
 * Writes src/models.ts from the public HTTP docs catalog.
 * Default: https://docs.x.ai/developers/models.md
 */

import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(fileURLToPath(new URL("..", import.meta.url)));
const OUT = path.join(ROOT, "src/models.ts");
const DEFAULT_URL = "https://docs.x.ai/developers/models.md";
const UA = "Mozilla/5.0 (compatible; xai-sdk-ts/0.1)";

function modelsUrl() {
  return process.env.XAI_MODELS_URL ?? DEFAULT_URL;
}

/** grok-4.6 → Grok46, grok-4-fast-reasoning → Grok4FastReasoning */
function modelKey(id) {
  const ident = id
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => {
      const cleaned = part.replaceAll(".", "").replaceAll(/[^A-Za-z0-9]/g, "");
      if (!cleaned) return "";
      return cleaned[0].toUpperCase() + cleaned.slice(1);
    })
    .join("");
  if (!ident) throw new Error(`cannot derive an identifier from model id ${JSON.stringify(id)}`);
  return /^[0-9]/.test(ident) ? `Model${ident}` : ident;
}

function isLanguageModelId(id) {
  return (
    id.startsWith("grok-") &&
    !/imagine|video|voice|speech|tts|stt|embedding/i.test(id)
  );
}

function collectIds(markdown) {
  /** @type {Map<string, string>} */
  const byKey = new Map();
  const add = (raw) => {
    const id = raw.trim().replace(/[).,;]+$/, "");
    if (!isLanguageModelId(id)) return;
    const key = modelKey(id);
    const existing = byKey.get(key);
    if (existing === undefined) byKey.set(key, id);
  };

  for (const match of markdown.matchAll(/grok-[a-z0-9]+(?:[._-][a-z0-9]+)*/gi)) {
    add(match[0]);
  }
  for (const match of markdown.matchAll(/\/developers\/models\/(grok-[a-z0-9._-]+)/gi)) {
    add(match[1]);
  }
  return byKey;
}

function render(byKey, sourceUrl, sourceHash) {
  const entries = [...byKey.entries()].sort(([a], [b]) => a.localeCompare(b));
  const body = entries.map(([key, id]) => `  ${key}: ${JSON.stringify(id)},`).join("\n");
  const fetchedAt = new Date().toISOString().slice(0, 10);
  return `/** Generated by \`pnpm generate:models\`. Do not edit by hand. */
/** Source: ${sourceUrl} (${fetchedAt}); SHA-256: ${sourceHash} */
export const models = {
${body}
} as const;

export type NamedModel = (typeof models)[keyof typeof models];
`;
}

async function main() {
  const url = modelsUrl();
  const response = await fetch(url, {
    headers: { accept: "*/*", "user-agent": UA },
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  const markdown = await response.text();
  const byKey = collectIds(markdown);
  if (byKey.size === 0) {
    throw new Error(`no language model ids found in ${url}`);
  }
  const sourceHash = createHash("sha256").update(markdown).digest("hex");
  await writeFile(OUT, render(byKey, url, sourceHash));
  console.error(`wrote ${byKey.size} models to src/models.ts`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
