#!/usr/bin/env node
/**
 * Writes src/version.ts from package.json so the compiled dist has a
 * string literal (no runtime JSON import).
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(fileURLToPath(new URL("..", import.meta.url)));
const pkg = JSON.parse(await readFile(path.join(ROOT, "package.json"), "utf8"));
const version = JSON.stringify(pkg.version);
const output = `/** Generated by \`pnpm generate:version\` from package.json. */\nexport const SDK_VERSION = ${version};\n`;
const outputPath = path.join(ROOT, "src/version.ts");

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) {
    throw new Error("src/version.ts is stale; run pnpm generate:version");
  }
} else {
  await writeFile(outputPath, output);
}
