#!/usr/bin/env node
/**
 * Writes src/generated/voice.ts from the Voice docs: the speech tags the REST reference lists
 * for `text`, the built-in voices in the text-to-speech guide's voice table, and the models in
 * the "Model Selection" tables of the speech-to-text and speech-to-speech guides.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(fileURLToPath(new URL("..", import.meta.url)));
const OUT = path.join(ROOT, "src/generated/voice.ts");
const DOCS = "https://docs.x.ai/developers";
const SOURCES = {
  reference: `${DOCS}/rest-api-reference/inference/voice.md`,
  textToSpeech: `${DOCS}/model-capabilities/audio/text-to-speech`,
  speechToText: `${DOCS}/model-capabilities/audio/speech-to-text.md`,
  speechToSpeech: `${DOCS}/model-capabilities/audio/speech-to-speech.md`,
};
const UA = "Mozilla/5.0 (compatible; xai-sdk-ts/0.1)";

async function load(url) {
  const response = await fetch(url, {
    headers: { accept: "*/*", "user-agent": UA },
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function collectTags(markdown, url) {
  const line = markdown.split("\n").find((candidate) => candidate.includes("Supports inline speech tags"));
  const inline = [...(line ?? "").matchAll(/\\?\[([a-z]+(?:-[a-z]+)*)\\?\]/g)].map((match) => match[1]);
  const wrapping = [...(line ?? "").matchAll(/\\?<([a-z]+(?:-[a-z]+)*)>/g)].map((match) => match[1]);
  if (inline.length === 0 || wrapping.length === 0) {
    throw new Error(`no speech tags found in ${url}`);
  }
  return { inline, wrapping };
}

function collectVoiceIds(html, url) {
  const rows = html.matchAll(/<tr><td><strong><code>([a-z0-9-]+)<\/code><\/strong><\/td>/g);
  const ids = [...new Set([...rows].map((match) => match[1]))].sort();
  if (!ids.includes("eve")) {
    throw new Error(`no voice table with the default voice eve found in ${url}`);
  }
  return ids;
}

function collectModelIds(markdown, url) {
  const section = markdown.split(/^## /m).find((part) => part.startsWith("Model Selection"));
  const ids = [...(section ?? "").matchAll(/^\| `([^`]+)` \|/gm)].map((match) => match[1]);
  if (ids.length === 0) {
    throw new Error(`no model table under "Model Selection" found in ${url}`);
  }
  return ids;
}

function tuple(values) {
  return `[\n${values.map((value) => `  ${JSON.stringify(value)},`).join("\n")}\n]`;
}

function union(values) {
  return values.map((value) => `  | ${JSON.stringify(value)}`).join("\n");
}

function render({ tags, voiceIds, transcriptionModels, realtimeModels }) {
  return `/**
 * Generated by \`pnpm generate:voice\`. Do not edit by hand.
 * Sources:
${Object.values(SOURCES).map((url) => ` * - ${url}`).join("\n")}
 */
export const INLINE_SPEECH_TAGS = ${tuple(tags.inline)} as const;

export const WRAPPING_SPEECH_TAGS = ${tuple(tags.wrapping)} as const;

export type InlineSpeechTags = [...typeof INLINE_SPEECH_TAGS];

export type WrappingSpeechTags = [...typeof WRAPPING_SPEECH_TAGS];

export type KnownVoiceId =
${union(voiceIds)};

/** Built-in voice IDs, plus any other string for custom voices and voices added after this SDK. */
export type VoiceId = KnownVoiceId | (string & {});

export type KnownTranscriptionModelId =
${union(transcriptionModels)};

/** Known transcription model IDs, plus any other string for models added after this SDK. */
export type TranscriptionModelId = KnownTranscriptionModelId | (string & {});

export type KnownRealtimeModelId =
${union(realtimeModels)};

/** Known realtime voice model IDs, plus any other string for models added after this SDK. */
export type RealtimeModelId = KnownRealtimeModelId | (string & {});
`;
}

async function main() {
  const [reference, textToSpeech, speechToText, speechToSpeech] = await Promise.all(
    Object.values(SOURCES).map(load),
  );
  const generated = {
    tags: collectTags(reference, SOURCES.reference),
    voiceIds: collectVoiceIds(textToSpeech, SOURCES.textToSpeech),
    transcriptionModels: collectModelIds(speechToText, SOURCES.speechToText),
    realtimeModels: collectModelIds(speechToSpeech, SOURCES.speechToSpeech),
  };
  await writeFile(OUT, render(generated));
  console.error(
    `wrote ${generated.tags.inline.length + generated.tags.wrapping.length} speech tags, ${generated.voiceIds.length} voices, ${generated.transcriptionModels.length} transcription models, and ${generated.realtimeModels.length} realtime models to src/generated/voice.ts`,
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
