/** Generated by `pnpm generate:models`. Do not edit by hand. */
/** Source: https://docs.x.ai/developers/models.md (2026-09-22); SHA-256: 1553ee7ff54b508f0b4b34b40d6f7c65f7a9e1205d51625c7b2876e321ac8233 */
export type KnownModelId =
  | "grok-4.20"
  | "grok-4.20-0309-non-reasoning"
  | "grok-4.20-0309-reasoning"
  | "grok-4.20-multi-agent"
  | "grok-4.20-multi-agent-0309"
  | "grok-4.3"
  | "grok-4.5"
  | "grok-4.6"
  | "grok-4.7"
  | "grok-build-0.1";

/** Known model IDs with a forward-compatible escape hatch for newer releases. */
export type ModelId = KnownModelId | (string & {});

export type KnownImageModelId =
  | "grok-imagine-image"
  | "grok-imagine-image-2.0"
  | "grok-imagine-image-quality";

/** Known image model IDs with a forward-compatible escape hatch for newer releases. */
export type ImageModelId = KnownImageModelId | (string & {});

export type KnownVideoModelId =
  | "grok-imagine-video"
  | "grok-imagine-video-1.5";

/** Known video model IDs with a forward-compatible escape hatch for newer releases. */
export type VideoModelId = KnownVideoModelId | (string & {});
