/** Generated by `pnpm generate:models`. Do not edit by hand. */
/** Source: https://docs.x.ai/developers/models.md (2026-08-27); SHA-256: 541ba863d9017f9d599a28bd216968a6149cc482e466b5f653d4fc1da0e2757d */
export const models = {
  Grok420: "grok-4.20",
  Grok4200309NonReasoning: "grok-4.20-0309-non-reasoning",
  Grok4200309Reasoning: "grok-4.20-0309-reasoning",
  Grok420MultiAgent0309: "grok-4.20-multi-agent-0309",
  Grok43: "grok-4.3",
  Grok45: "grok-4.5",
  Grok46: "grok-4.6",
  GrokBuild01: "grok-build-0.1",
} as const;

export type NamedModel = (typeof models)[keyof typeof models];
