/** Generated by `pnpm generate:models`. Do not edit by hand. */
/** Source: https://docs.x.ai/developers/models.md (2026-08-27); SHA-256: c14f18792bef439c6645f21872d5ff2b00aa8ec236f7a24f61c35d97eae33af3 */
export type KnownModelId =
  | "grok-4.20"
  | "grok-4.20-0309-non-reasoning"
  | "grok-4.20-0309-reasoning"
  | "grok-4.20-multi-agent-0309"
  | "grok-4.3"
  | "grok-4.5"
  | "grok-4.6"
  | "grok-build-0.1";

/** Known model IDs with a forward-compatible escape hatch for newer releases. */
export type ModelId = KnownModelId | (string & {});
